from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SuccessResponseDeletedBookData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None):  # noqa: E501
        """SuccessResponseDeletedBookData - a model defined in OpenAPI

        :param id: The id of this SuccessResponseDeletedBookData.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'id': int
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessResponseDeletedBookData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse_DeletedBook_data of this SuccessResponseDeletedBookData.  # noqa: E501
        :rtype: SuccessResponseDeletedBookData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SuccessResponseDeletedBookData.


        :return: The id of this SuccessResponseDeletedBookData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SuccessResponseDeletedBookData.


        :param id: The id of this SuccessResponseDeletedBookData.
        :type id: int
        """

        self._id = id
