from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, message=None, error=None):  # noqa: E501
        """ErrorResponse - a model defined in OpenAPI

        :param success: The success of this ErrorResponse.  # noqa: E501
        :type success: bool
        :param message: The message of this ErrorResponse.  # noqa: E501
        :type message: str
        :param error: The error of this ErrorResponse.  # noqa: E501
        :type error: object
        """
        self.openapi_types = {
            'success': bool,
            'message': str,
            'error': object
        }

        self.attribute_map = {
            'success': 'success',
            'message': 'message',
            'error': 'error'
        }

        self._success = success
        self._message = message
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this ErrorResponse.


        :return: The success of this ErrorResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this ErrorResponse.


        :param success: The success of this ErrorResponse.
        :type success: bool
        """

        self._success = success

    @property
    def message(self) -> str:
        """Gets the message of this ErrorResponse.


        :return: The message of this ErrorResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ErrorResponse.


        :param message: The message of this ErrorResponse.
        :type message: str
        """

        self._message = message

    @property
    def error(self) -> object:
        """Gets the error of this ErrorResponse.


        :return: The error of this ErrorResponse.
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error: object):
        """Sets the error of this ErrorResponse.


        :param error: The error of this ErrorResponse.
        :type error: object
        """

        self._error = error
